"""
Execution of data_manipulation.py
"""
import os
import zipfile
from zipfile import ZipFile
from mapping.data_manipulation import init_index, init_txt, init_csv, init_docx, get_data

MAIN_PATH = os.path.split(os.path.realpath(__file__))[0]


def prepare_archive():
    """
    This function creates an archive storing all the outputs generated by
    map_comments_with_proposals
    """
    dir_path = os.path.join(MAIN_PATH, "dist")
    files = os.listdir(dir_path)
    files.remove('.gitkeep')
    with ZipFile("comments_mapping_outputs.zip", "w") as new_zip:
        for file in files:
            new_zip.write(os.path.relpath(os.path.join(dir_path, file)))


def map_comments_with_proposals(json_object, sorting_attribute=None):
    df_proposals, df_comments = get_data(json_object)
    hsh_prop = init_index(proposals_dataframe=df_proposals, comments_dataframe=df_comments)
    init_csv(hsh_prop)
    init_txt(hsh_prop, sorting_attribute=sorting_attribute)
    init_docx(hsh_prop, sorting_attribute=sorting_attribute)
    prepare_archive()
